#!/bin/sh

# install perl modules for fcgi deployment
# of web application.

cpanm=$1
APP_DIR=$2

cd $2
echo "------> Installing dependencies ......... "

echo "------> Installing DBIx::Class 0.08127"
carton install http://cpan.metacpan.org/authors/id/A/AB/ABRAXXA/DBIx-Class-0.08127.tar.gz

echo " -----> Installing modware"
curl -o modware.tar.gz -s -k -L https://github.com/dictyBase/Modware/tarball/develop \
    && carton install modware.tar.gz && rm modware.tar.gz

echo " ----> Installing mojolicious 1.21"
curl -o mojolicious.tar.gz -s -k -L https://github.com/kraih/mojo/tarball/v1.21 \
    && carton install mojolicious.tar.gz && rm mojolicious.tar.gz

carton install

echo "------> Installing plack and dependencies for fcgi deployment"
carton install FCGI::ProcManager
